### ISSUE TITLE
Crash when importing tinycss>=1.0.0

### ISSUE THREAD

**Issue by Polsaker** [Kozea/tinycss2#11]
This happens only when importing it from a project that runs with Flask/eventlet

```
Traceback (most recent call last):
  File "/home/polsaker/old/home/polsaker/body/throat/app/misc.py", line 15, in <module>
    import tinycss2
  File "/home/polsaker/.pyenv/versions/throat37/lib/python3.7/site-packages/tinycss2/__init__.py", line 10, in <module>
    VERSION = __version__ = (Path(__file__).parent / 'VERSION').read_text()
  File "/home/polsaker/.pyenv/versions/3.7.2/lib/python3.7/pathlib.py", line 1189, in read_text
    with self.open(mode='r', encoding=encoding, errors=errors) as f:
  File "/home/polsaker/.pyenv/versions/3.7.2/lib/python3.7/pathlib.py", line 1176, in open
    opener=self._opener)
  File "/home/polsaker/.pyenv/versions/3.7.2/lib/python3.7/pathlib.py", line 1030, in _opener
    return self._accessor.open(self, flags, mode)
  File "/home/polsaker/.pyenv/versions/throat37/lib/python3.7/site-packages/eventlet/green/os.py", line 107, in open
    fd = __original_open__(file, flags, mode, dir_fd=dir_fd)
TypeError: open: path should be string, bytes or os.PathLike, not _NormalAccessor
```

**Comment by liZe** [comment]
This is a bug in eventlet: eventlet/eventlet#534. Looks like eventlet monkey-patches `os.open` in a way that doesn't work anymore with Python 3.7.

Monkey-patching the standard library is bad :bomb: :smile:.
