### ISSUE TITLE
ModuleNotFoundError: No module named 'flit_core.dummy'

### ISSUE THREAD

**Issue by createcandle** [Kozea/tinycss2#46]
I'm running into this issue when [building a project](https://github.com/createcandle/privacy-manager/blob/master/package.sh). I tried it on multiple devices with both python 3.7 and 3.9. I tried installing flit too. But the issue remains.

Oddly, the project compiled ok two weeks ago.

```
Successfully installed certifi-2021.10.8 charset_normalizer-2.0.12 docutils-0.18.1 flit-3.7.0 flit_core-3.7.0 idna-3.3 requests-2.27.1 tomli-2.0.1 tomli-w-1.0.0 urllib3-1.26.8
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting cssselect2
  Downloading cssselect2-0.4.1.tar.gz (32 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... error
  error: subprocess-exited-with-error
  
  × pip subprocess to install backend dependencies did not run successfully.
  │ exit code: 1
  ╰─> [58 lines of output]
      Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple, https://www.piwheels.org/simple
      Ignoring pytest-cov: markers 'extra == "test"' don't match your environment
      Ignoring coverage: markers 'extra == "test"' don't match your environment
      Ignoring sphinx: markers 'extra == "doc"' don't match your environment
      Ignoring pytest-flake8: markers 'extra == "test"' don't match your environment
      Ignoring sphinx_rtd_theme: markers 'extra == "doc"' don't match your environment
      Ignoring pytest-isort: markers 'extra == "test"' don't match your environment
      Ignoring pytest: markers 'extra == "test"' don't match your environment
      Collecting webencodings
        Downloading webencodings-0.5.1.tar.gz (9.7 kB)
        Preparing metadata (setup.py): started
        Preparing metadata (setup.py): finished with status 'done'
      Collecting tinycss2
        Downloading tinycss2-1.1.1.tar.gz (65 kB)
           ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.7/65.7 KB 4.0 MB/s eta 0:00:00
        Installing build dependencies: started
        Installing build dependencies: finished with status 'done'
        Getting requirements to build wheel: started
        Getting requirements to build wheel: finished with status 'done'
        Installing backend dependencies: started
        Installing backend dependencies: finished with status 'done'
        Preparing metadata (pyproject.toml): started
        Preparing metadata (pyproject.toml): finished with status 'error'
        error: subprocess-exited-with-error
      
        × Preparing metadata (pyproject.toml) did not run successfully.
        │ exit code: 1
        ╰─> [20 lines of output]
            Traceback (most recent call last):
              File "/tmp/tmpt2owjxd1_in_process.py", line 363, in <module>
                main()
              File "/tmp/tmpt2owjxd1_in_process.py", line 345, in main
                json_out['return_val'] = hook(**hook_input['kwargs'])
              File "/tmp/tmpt2owjxd1_in_process.py", line 164, in prepare_metadata_for_build_wheel
                return hook(metadata_directory, config_settings)
              File "/tmp/pip-build-env-9yfqr55v/overlay/lib/python3.9/site-packages/flit_core/buildapi.py", line 49, in prepare_metadata_for_build_wheel
                metadata = make_metadata(module, ini_info)
              File "/tmp/pip-build-env-9yfqr55v/overlay/lib/python3.9/site-packages/flit_core/common.py", line 399, in make_metadata
                md_dict.update(get_info_from_module(module, ini_info.dynamic_metadata))
              File "/tmp/pip-build-env-9yfqr55v/overlay/lib/python3.9/site-packages/flit_core/common.py", line 196, in get_info_from_module
                docstring, version = get_docstring_and_version_via_import(target)
              File "/tmp/pip-build-env-9yfqr55v/overlay/lib/python3.9/site-packages/flit_core/common.py", line 171, in get_docstring_and_version_via_import
                spec.loader.exec_module(m)
              File "<frozen importlib._bootstrap_external>", line 790, in exec_module
              File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
              File "/tmp/pip-install-uke6pn2d/tinycss2_6e2a8a596ac441fb813690611484c4dc/tinycss2/__init__.py", line 11, in <module>
                from .bytes import parse_stylesheet_bytes  # noqa
            ModuleNotFoundError: No module named 'flit_core.dummy'
            [end of output]

```

**Comment by liZe** [comment]
Hello.

That’s a bug in flit: https://github.com/pypa/flit/issues/530.
